# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       zsh

# >> macros
# << macros

Summary:    The Z shell
Version:    5.0.2
Release:    2
Group:      Applications/System
License:    MIT
URL:        https://github.com/thp/mer-tools-zsh
Source0:    zsh-%{version}.tar.bz2
Source100:  zsh.yaml
Patch0:     0001-Disable-building-and-installing-documentation.patch
BuildRequires:  pkgconfig(ncursesw)
BuildRequires:  pkgconfig(libpcre)
BuildRequires:  libcap-devel
BuildRequires:  texinfo
BuildRequires:  groff
BuildRequires:  autoconf

%description
Zsh is a shell designed for interactive use, although
it is also a powerful scripting language. Many of the
useful features of bash, ksh, and tcsh were incorporated
into zsh; many original features were added.



%prep
%setup -q -n src

# 0001-Disable-building-and-installing-documentation.patch
%patch0 -p1
# >> setup
# << setup

%build
# >> build pre
%define _bindir /bin
autoreconf
# << build pre

%configure --disable-static \
    --enable-etcdir=%{_sysconfdir} \
    --with-tcsetpgrp \
    --bindir=/bin

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post


%post
# >> post
# Taken from Fedora's zsh-5.0.2-1 package
if [ ! -f %{_sysconfdir}/shells ] ; then
echo "%{_bindir}/zsh" > %{_sysconfdir}/shells
else
grep -q "^%{_bindir}/zsh$" %{_sysconfdir}/shells || echo "%{_bindir}/zsh" >> %{_sysconfdir}/shells
fi
# << post

%postun
# >> postun
# Taken from Fedora's zsh-5.0.2-1 package
if [ "$1" = 0 ] ; then
if [ -f %{_sysconfdir}/shells ] ; then
TmpFile=`%{_bindir}/mktemp /tmp/.zshrpmXXXXXX`
grep -v '^%{_bindir}/zsh$' %{_sysconfdir}/shells > $TmpFile
cp -f $TmpFile %{_sysconfdir}/shells
rm -f $TmpFile
fi
fi
# << postun

%files
%defattr(-,root,root,-)
%{_datadir}/zsh/%{version}/scripts/*
%{_datadir}/zsh/%{version}/functions/*
%{_libdir}/zsh/5.0.2/zsh/*.so
%{_libdir}/zsh/5.0.2/zsh/net/*.so
%{_bindir}/zsh*
# >> files
# << files
